name: Checkout PR
description: Fetch and checkout a pull request
author: dawidd6
branding:
  icon: git-pull-request
  color: purple
inputs:
  github_token:
    description: Github token
    required: false
    default: ${{github.token}}
  pr:
    description: Pull request number
    required: true
  repo:
    description: Repository name with owner (like actions/checkout)
    required: false
    default: ${{github.repository}}
runs:
  using: node12
  main: main.js
