name: Test Action

on: push

jobs:
  test-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: action
      - name: Checkout other repo
        uses: actions/checkout@v2
        with:
          repo: dawidd6/homebrew-test
      - name: Checkout PR
        uses: ./action
        with:
          pr: 12
          repo: dawidd6/homebrew-test
      - name: Test
        run: |
          git config --local --get-regexp '^branch.+'
          git push
  test-this-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout PR
        uses: ./
        with:
          pr: 1
      - name: Test
        run: |
          git config --local --get-regexp '^branch.+'
          git push