name: Test Action

on: push

jobs:
  test-other-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout other repo
        uses: actions/checkout@v2
        with:
          repo: dawidd6/homebrew-test
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          path: action
      - name: Checkout PR
        uses: ./action
        with:
          github_token: ${{secrets.TOKEN}}
          pr: 12
          repo: dawidd6/homebrew-test
      - name: Show config
        run: |
          git config --list
      - name: Push back
        run: |
          git push -v
  test-this-repo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout PR
        uses: ./
        with:
          pr: 1
      - name: Show config
        run: |
          git config --list
      - name: Push back
        run: |
          git push -v